using System;

namespace ISOCodex.Currency;

// <auto-generated />
// Generated by scripts/update-currency-data.ps1 from data/source/currency-data.manifest.json.
/// <summary>
/// Exposes runtime-visible provenance for the packaged currency data.
/// </summary>
public static class CurrencyDataVersion
{
    /// <summary>Gets the version identifier for the packaged currency data.</summary>
    public static string Identifier { get; } = "iso4217-cldr-2026-06-22-c1f3aaea";

    /// <summary>Gets the date this source snapshot was checked, expressed as UTC midnight.</summary>
    public static DateTime CheckedOn { get; } = new DateTime(2026, 6, 22, 0, 0, 0, DateTimeKind.Utc);

    /// <summary>Gets a description of the packaged currency data source.</summary>
    public static string Description { get; } = "Pinned SIX ISO 4217 List One and Unicode CLDR supplemental currency data snapshot generated via scripts/build-currency-data-snapshot.ps1; derived JSON normalized UTF-8/LF SHA-256 c1f3aaea54949be9a7399a105dd61917a293dafb73171b9c1d3f6cf0b9179f95; not an official ISO 4217 redistribution.";

    /// <summary>Gets the kind of source used for the packaged currency data.</summary>
    public static string SourceKind { get; } = "SIX-ISO4217+Unicode-CLDR";
}
