using System;
using System.Collections.Generic;
using System.Linq;

namespace ISOCodex.Currency;

// <auto-generated />
// Generated by scripts/update-currency-data.ps1 from data/source/currency-data.snapshot.json.
// Pinned by data/source/currency-data.manifest.json.
// Normalized source SHA-256: c1f3aaea54949be9a7399a105dd61917a293dafb73171b9c1d3f6cf0b9179f95.
// Review data/source/README.md before changing the source snapshot.
internal static class CurrencyData
{
    internal const string SourceSnapshot = "data/source/currency-data.snapshot.json";
    internal const string SourceSha256 = "c1f3aaea54949be9a7399a105dd61917a293dafb73171b9c1d3f6cf0b9179f95";
    internal const int SourceEntryCount = 178;

    private static readonly CurrencyDataEntry[] Entries =
    {
        new("AED", "784", "UAE Dirham", 2, CurrencyKind.NationalCurrency, true, new[] { "AE" }, null, null),
        new("AFN", "971", "Afghani", 2, CurrencyKind.NationalCurrency, true, new[] { "AF" }, null, null),
        new("ALL", "008", "Lek", 2, CurrencyKind.NationalCurrency, true, new[] { "AL" }, null, null),
        new("AMD", "051", "Armenian Dram", 2, CurrencyKind.NationalCurrency, true, new[] { "AM" }, 0, null),
        new("AOA", "973", "Kwanza", 2, CurrencyKind.NationalCurrency, true, new[] { "AO" }, null, null),
        new("ARS", "032", "Argentine Peso", 2, CurrencyKind.NationalCurrency, true, new[] { "AR" }, null, null),
        new("AUD", "036", "Australian Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "AU", "CC", "CX", "HM", "KI", "NF", "NR", "TV" }, null, null),
        new("AWG", "533", "Aruban Florin", 2, CurrencyKind.NationalCurrency, true, new[] { "AW" }, null, null),
        new("AZN", "944", "Azerbaijan Manat", 2, CurrencyKind.NationalCurrency, true, new[] { "AZ" }, null, null),
        new("BAM", "977", "Convertible Mark", 2, CurrencyKind.NationalCurrency, true, new[] { "BA" }, null, null),
        new("BBD", "052", "Barbados Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "BB" }, null, null),
        new("BDT", "050", "Taka", 2, CurrencyKind.NationalCurrency, true, new[] { "BD" }, null, null),
        new("BHD", "048", "Bahraini Dinar", 3, CurrencyKind.NationalCurrency, true, new[] { "BH" }, null, null),
        new("BIF", "108", "Burundi Franc", 0, CurrencyKind.NationalCurrency, true, new[] { "BI" }, null, null),
        new("BMD", "060", "Bermudian Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "BM" }, null, null),
        new("BND", "096", "Brunei Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "BN" }, null, null),
        new("BOB", "068", "Boliviano", 2, CurrencyKind.NationalCurrency, true, new[] { "BO" }, null, null),
        new("BOV", "984", "Mvdol", 2, CurrencyKind.Fund, false, Array.Empty<string>(), null, null),
        new("BRL", "986", "Brazilian Real", 2, CurrencyKind.NationalCurrency, true, new[] { "BR" }, null, null),
        new("BSD", "044", "Bahamian Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "BS" }, null, null),
        new("BTN", "064", "Ngultrum", 2, CurrencyKind.NationalCurrency, true, new[] { "BT" }, null, null),
        new("BWP", "072", "Pula", 2, CurrencyKind.NationalCurrency, true, new[] { "BW" }, null, null),
        new("BYN", "933", "Belarusian Ruble", 2, CurrencyKind.NationalCurrency, true, new[] { "BY" }, null, null),
        new("BZD", "084", "Belize Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "BZ" }, null, null),
        new("CAD", "124", "Canadian Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "CA" }, null, 0.05m),
        new("CDF", "976", "Congolese Franc", 2, CurrencyKind.NationalCurrency, true, new[] { "CD" }, null, null),
        new("CHE", "947", "WIR Euro", 2, CurrencyKind.Fund, false, Array.Empty<string>(), null, null),
        new("CHF", "756", "Swiss Franc", 2, CurrencyKind.NationalCurrency, true, new[] { "CH", "LI" }, null, 0.05m),
        new("CHW", "948", "WIR Franc", 2, CurrencyKind.Fund, false, Array.Empty<string>(), null, null),
        new("CLF", "990", "Unidad de Fomento", 4, CurrencyKind.Fund, false, Array.Empty<string>(), null, null),
        new("CLP", "152", "Chilean Peso", 0, CurrencyKind.NationalCurrency, true, new[] { "CL" }, null, null),
        new("CNY", "156", "Yuan Renminbi", 2, CurrencyKind.NationalCurrency, true, new[] { "CN" }, null, null),
        new("COP", "170", "Colombian Peso", 2, CurrencyKind.NationalCurrency, true, new[] { "CO" }, null, null),
        new("COU", "970", "Unidad de Valor Real", 2, CurrencyKind.Fund, false, Array.Empty<string>(), null, null),
        new("CRC", "188", "Costa Rican Colon", 2, CurrencyKind.NationalCurrency, true, new[] { "CR" }, 0, null),
        new("CUP", "192", "Cuban Peso", 2, CurrencyKind.NationalCurrency, true, new[] { "CU" }, null, null),
        new("CVE", "132", "Cabo Verde Escudo", 2, CurrencyKind.NationalCurrency, true, new[] { "CV" }, null, null),
        new("CZK", "203", "Czech Koruna", 2, CurrencyKind.NationalCurrency, true, new[] { "CZ" }, 0, null),
        new("DJF", "262", "Djibouti Franc", 0, CurrencyKind.NationalCurrency, true, new[] { "DJ" }, null, null),
        new("DKK", "208", "Danish Krone", 2, CurrencyKind.NationalCurrency, true, new[] { "DK", "FO", "GL" }, null, 0.5m),
        new("DOP", "214", "Dominican Peso", 2, CurrencyKind.NationalCurrency, true, new[] { "DO" }, null, null),
        new("DZD", "012", "Algerian Dinar", 2, CurrencyKind.NationalCurrency, true, new[] { "DZ" }, null, null),
        new("EGP", "818", "Egyptian Pound", 2, CurrencyKind.NationalCurrency, true, new[] { "EG" }, null, null),
        new("ERN", "232", "Nakfa", 2, CurrencyKind.NationalCurrency, true, new[] { "ER" }, null, null),
        new("ETB", "230", "Ethiopian Birr", 2, CurrencyKind.NationalCurrency, true, new[] { "ET" }, null, null),
        new("EUR", "978", "Euro", 2, CurrencyKind.NationalCurrency, true, new[] { "AD", "AT", "AX", "BE", "BG", "BL", "CY", "DE", "EA", "EE", "ES", "EU", "FI", "FR", "GF", "GP", "GR", "HR", "IC", "IE", "IT", "LT", "LU", "LV", "MC", "ME", "MF", "MQ", "MT", "NL", "PM", "PT", "RE", "SI", "SK", "SM", "TF", "VA", "XK", "YT" }, null, null),
        new("FJD", "242", "Fiji Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "FJ" }, null, null),
        new("FKP", "238", "Falkland Islands Pound", 2, CurrencyKind.NationalCurrency, true, new[] { "FK" }, null, null),
        new("GBP", "826", "Pound Sterling", 2, CurrencyKind.NationalCurrency, true, new[] { "GB", "GG", "GS", "IM", "JE", "TA" }, null, null),
        new("GEL", "981", "Lari", 2, CurrencyKind.NationalCurrency, true, new[] { "GE" }, null, null),
        new("GHS", "936", "Ghana Cedi", 2, CurrencyKind.NationalCurrency, true, new[] { "GH" }, null, null),
        new("GIP", "292", "Gibraltar Pound", 2, CurrencyKind.NationalCurrency, true, new[] { "GI" }, null, null),
        new("GMD", "270", "Dalasi", 2, CurrencyKind.NationalCurrency, true, new[] { "GM" }, null, null),
        new("GNF", "324", "Guinean Franc", 0, CurrencyKind.NationalCurrency, true, new[] { "GN" }, null, null),
        new("GTQ", "320", "Quetzal", 2, CurrencyKind.NationalCurrency, true, new[] { "GT" }, null, null),
        new("GYD", "328", "Guyana Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "GY" }, 0, null),
        new("HKD", "344", "Hong Kong Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "HK" }, null, null),
        new("HNL", "340", "Lempira", 2, CurrencyKind.NationalCurrency, true, new[] { "HN" }, null, null),
        new("HTG", "332", "Gourde", 2, CurrencyKind.NationalCurrency, true, new[] { "HT" }, null, null),
        new("HUF", "348", "Forint", 2, CurrencyKind.NationalCurrency, true, new[] { "HU" }, 0, 5m),
        new("IDR", "360", "Rupiah", 2, CurrencyKind.NationalCurrency, true, new[] { "ID" }, null, null),
        new("ILS", "376", "New Israeli Sheqel", 2, CurrencyKind.NationalCurrency, true, new[] { "IL", "PS" }, null, null),
        new("INR", "356", "Indian Rupee", 2, CurrencyKind.NationalCurrency, true, new[] { "BT", "IN" }, null, null),
        new("IQD", "368", "Iraqi Dinar", 3, CurrencyKind.NationalCurrency, true, new[] { "IQ" }, null, null),
        new("IRR", "364", "Iranian Rial", 2, CurrencyKind.NationalCurrency, true, new[] { "IR" }, null, null),
        new("ISK", "352", "Iceland Krona", 0, CurrencyKind.NationalCurrency, true, new[] { "IS" }, null, null),
        new("JMD", "388", "Jamaican Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "JM" }, null, null),
        new("JOD", "400", "Jordanian Dinar", 3, CurrencyKind.NationalCurrency, true, new[] { "JO", "PS" }, null, null),
        new("JPY", "392", "Yen", 0, CurrencyKind.NationalCurrency, true, new[] { "JP" }, null, null),
        new("KES", "404", "Kenyan Shilling", 2, CurrencyKind.NationalCurrency, true, new[] { "KE" }, null, null),
        new("KGS", "417", "Som", 2, CurrencyKind.NationalCurrency, true, new[] { "KG" }, null, null),
        new("KHR", "116", "Riel", 2, CurrencyKind.NationalCurrency, true, new[] { "KH" }, null, null),
        new("KMF", "174", "Comorian Franc", 0, CurrencyKind.NationalCurrency, true, new[] { "KM" }, null, null),
        new("KPW", "408", "North Korean Won", 2, CurrencyKind.NationalCurrency, true, new[] { "KP" }, null, null),
        new("KRW", "410", "Won", 0, CurrencyKind.NationalCurrency, true, new[] { "KR" }, null, null),
        new("KWD", "414", "Kuwaiti Dinar", 3, CurrencyKind.NationalCurrency, true, new[] { "KW" }, null, null),
        new("KYD", "136", "Cayman Islands Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "KY" }, null, null),
        new("KZT", "398", "Tenge", 2, CurrencyKind.NationalCurrency, true, new[] { "KZ" }, null, null),
        new("LAK", "418", "Lao Kip", 2, CurrencyKind.NationalCurrency, true, new[] { "LA" }, null, null),
        new("LBP", "422", "Lebanese Pound", 2, CurrencyKind.NationalCurrency, true, new[] { "LB" }, null, null),
        new("LKR", "144", "Sri Lanka Rupee", 2, CurrencyKind.NationalCurrency, true, new[] { "LK" }, null, null),
        new("LRD", "430", "Liberian Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "LR" }, null, null),
        new("LSL", "426", "Loti", 2, CurrencyKind.NationalCurrency, true, new[] { "LS" }, null, null),
        new("LYD", "434", "Libyan Dinar", 3, CurrencyKind.NationalCurrency, true, new[] { "LY" }, null, null),
        new("MAD", "504", "Moroccan Dirham", 2, CurrencyKind.NationalCurrency, true, new[] { "EH", "MA" }, null, null),
        new("MDL", "498", "Moldovan Leu", 2, CurrencyKind.NationalCurrency, true, new[] { "MD" }, null, null),
        new("MGA", "969", "Malagasy Ariary", 2, CurrencyKind.NationalCurrency, true, new[] { "MG" }, null, null),
        new("MKD", "807", "Denar", 2, CurrencyKind.NationalCurrency, true, new[] { "MK" }, null, null),
        new("MMK", "104", "Kyat", 2, CurrencyKind.NationalCurrency, true, new[] { "MM" }, null, null),
        new("MNT", "496", "Tugrik", 2, CurrencyKind.NationalCurrency, true, new[] { "MN" }, 0, null),
        new("MOP", "446", "Pataca", 2, CurrencyKind.NationalCurrency, true, new[] { "MO" }, null, null),
        new("MRU", "929", "Ouguiya", 2, CurrencyKind.NationalCurrency, true, new[] { "MR" }, 2, 0.2m),
        new("MUR", "480", "Mauritius Rupee", 2, CurrencyKind.NationalCurrency, true, new[] { "MU" }, 0, null),
        new("MVR", "462", "Rufiyaa", 2, CurrencyKind.NationalCurrency, true, new[] { "MV" }, null, null),
        new("MWK", "454", "Malawi Kwacha", 2, CurrencyKind.NationalCurrency, true, new[] { "MW" }, null, null),
        new("MXN", "484", "Mexican Peso", 2, CurrencyKind.NationalCurrency, true, new[] { "MX" }, null, null),
        new("MXV", "979", "Mexican Unidad de Inversion (UDI)", 2, CurrencyKind.Fund, false, Array.Empty<string>(), null, null),
        new("MYR", "458", "Malaysian Ringgit", 2, CurrencyKind.NationalCurrency, true, new[] { "MY" }, null, null),
        new("MZN", "943", "Mozambique Metical", 2, CurrencyKind.NationalCurrency, true, new[] { "MZ" }, null, null),
        new("NAD", "516", "Namibia Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "NA" }, null, null),
        new("NGN", "566", "Naira", 2, CurrencyKind.NationalCurrency, true, new[] { "NG" }, null, null),
        new("NIO", "558", "Cordoba Oro", 2, CurrencyKind.NationalCurrency, true, new[] { "NI" }, null, null),
        new("NOK", "578", "Norwegian Krone", 2, CurrencyKind.NationalCurrency, true, new[] { "BV", "NO", "SJ" }, 0, null),
        new("NPR", "524", "Nepalese Rupee", 2, CurrencyKind.NationalCurrency, true, new[] { "NP" }, null, null),
        new("NZD", "554", "New Zealand Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "CK", "NU", "NZ", "PN", "TK" }, null, null),
        new("OMR", "512", "Rial Omani", 3, CurrencyKind.NationalCurrency, true, new[] { "OM" }, null, null),
        new("PAB", "590", "Balboa", 2, CurrencyKind.NationalCurrency, true, new[] { "PA" }, null, null),
        new("PEN", "604", "Sol", 2, CurrencyKind.NationalCurrency, true, new[] { "PE" }, null, null),
        new("PGK", "598", "Kina", 2, CurrencyKind.NationalCurrency, true, new[] { "PG" }, null, null),
        new("PHP", "608", "Philippine Peso", 2, CurrencyKind.NationalCurrency, true, new[] { "PH" }, null, null),
        new("PKR", "586", "Pakistan Rupee", 2, CurrencyKind.NationalCurrency, true, new[] { "PK" }, null, null),
        new("PLN", "985", "Zloty", 2, CurrencyKind.NationalCurrency, true, new[] { "PL" }, null, null),
        new("PYG", "600", "Guarani", 0, CurrencyKind.NationalCurrency, true, new[] { "PY" }, null, null),
        new("QAR", "634", "Qatari Rial", 2, CurrencyKind.NationalCurrency, true, new[] { "QA" }, null, null),
        new("RON", "946", "Romanian Leu", 2, CurrencyKind.NationalCurrency, true, new[] { "RO" }, null, null),
        new("RSD", "941", "Serbian Dinar", 2, CurrencyKind.NationalCurrency, true, new[] { "RS" }, 0, null),
        new("RUB", "643", "Russian Ruble", 2, CurrencyKind.NationalCurrency, true, new[] { "RU" }, null, null),
        new("RWF", "646", "Rwanda Franc", 0, CurrencyKind.NationalCurrency, true, new[] { "RW" }, null, null),
        new("SAR", "682", "Saudi Riyal", 2, CurrencyKind.NationalCurrency, true, new[] { "SA" }, null, null),
        new("SBD", "090", "Solomon Islands Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "SB" }, null, null),
        new("SCR", "690", "Seychelles Rupee", 2, CurrencyKind.NationalCurrency, true, new[] { "SC" }, null, null),
        new("SDG", "938", "Sudanese Pound", 2, CurrencyKind.NationalCurrency, true, new[] { "SD" }, null, null),
        new("SEK", "752", "Swedish Krona", 2, CurrencyKind.NationalCurrency, true, new[] { "SE" }, 0, null),
        new("SGD", "702", "Singapore Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "SG" }, null, null),
        new("SHP", "654", "Saint Helena Pound", 2, CurrencyKind.NationalCurrency, true, new[] { "AC", "SH" }, null, null),
        new("SLE", "925", "Leone", 2, CurrencyKind.NationalCurrency, true, new[] { "SL" }, null, null),
        new("SOS", "706", "Somali Shilling", 2, CurrencyKind.NationalCurrency, true, new[] { "SO" }, null, null),
        new("SRD", "968", "Surinam Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "SR" }, null, null),
        new("SSP", "728", "South Sudanese Pound", 2, CurrencyKind.NationalCurrency, true, new[] { "SS" }, null, null),
        new("STN", "930", "Dobra", 2, CurrencyKind.NationalCurrency, true, new[] { "ST" }, null, null),
        new("SVC", "222", "El Salvador Colon", 2, CurrencyKind.NationalCurrency, false, Array.Empty<string>(), null, null),
        new("SYP", "760", "Syrian Pound", 2, CurrencyKind.NationalCurrency, true, new[] { "SY" }, null, null),
        new("SZL", "748", "Lilangeni", 2, CurrencyKind.NationalCurrency, true, new[] { "SZ" }, null, null),
        new("THB", "764", "Baht", 2, CurrencyKind.NationalCurrency, true, new[] { "TH" }, null, null),
        new("TJS", "972", "Somoni", 2, CurrencyKind.NationalCurrency, true, new[] { "TJ" }, null, null),
        new("TMT", "934", "Turkmenistan New Manat", 2, CurrencyKind.NationalCurrency, true, new[] { "TM" }, null, null),
        new("TND", "788", "Tunisian Dinar", 3, CurrencyKind.NationalCurrency, true, new[] { "TN" }, null, null),
        new("TOP", "776", "Pa’anga", 2, CurrencyKind.NationalCurrency, true, new[] { "TO" }, null, null),
        new("TRY", "949", "Turkish Lira", 2, CurrencyKind.NationalCurrency, true, new[] { "TR" }, null, null),
        new("TTD", "780", "Trinidad and Tobago Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "TT" }, null, null),
        new("TWD", "901", "New Taiwan Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "TW" }, 0, null),
        new("TZS", "834", "Tanzanian Shilling", 2, CurrencyKind.NationalCurrency, true, new[] { "TZ" }, 0, null),
        new("UAH", "980", "Hryvnia", 2, CurrencyKind.NationalCurrency, true, new[] { "UA" }, null, null),
        new("UGX", "800", "Uganda Shilling", 0, CurrencyKind.NationalCurrency, true, new[] { "UG" }, null, null),
        new("USD", "840", "US Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "AS", "BQ", "DG", "EC", "FM", "GU", "HT", "IO", "MH", "MP", "PA", "PR", "PW", "SV", "TC", "TL", "UM", "US", "VG", "VI", "ZW" }, null, null),
        new("USN", "997", "US Dollar (Next day)", 2, CurrencyKind.Fund, false, Array.Empty<string>(), null, null),
        new("UYI", "940", "Uruguay Peso en Unidades Indexadas (UI)", 0, CurrencyKind.Fund, false, Array.Empty<string>(), null, null),
        new("UYU", "858", "Peso Uruguayo", 2, CurrencyKind.NationalCurrency, true, new[] { "UY" }, null, null),
        new("UYW", "927", "Unidad Previsional", 4, CurrencyKind.Fund, false, Array.Empty<string>(), null, null),
        new("UZS", "860", "Uzbekistan Sum", 2, CurrencyKind.NationalCurrency, true, new[] { "UZ" }, 0, null),
        new("VED", "926", "Bolívar Soberano", 2, CurrencyKind.NationalCurrency, false, Array.Empty<string>(), null, null),
        new("VES", "928", "Bolívar Soberano", 2, CurrencyKind.NationalCurrency, true, new[] { "VE" }, null, null),
        new("VND", "704", "Dong", 0, CurrencyKind.NationalCurrency, true, new[] { "VN" }, null, null),
        new("VUV", "548", "Vatu", 0, CurrencyKind.NationalCurrency, true, new[] { "VU" }, null, null),
        new("WST", "882", "Tala", 2, CurrencyKind.NationalCurrency, true, new[] { "WS" }, null, null),
        new("XAD", "396", "Arab Accounting Dinar", 2, CurrencyKind.Fund, false, Array.Empty<string>(), null, null),
        new("XAF", "950", "CFA Franc BEAC", 0, CurrencyKind.NationalCurrency, true, new[] { "CF", "CG", "CM", "GA", "GQ", "TD" }, null, null),
        new("XAG", "961", "Silver", null, CurrencyKind.PreciousMetal, false, Array.Empty<string>(), null, null),
        new("XAU", "959", "Gold", null, CurrencyKind.PreciousMetal, false, Array.Empty<string>(), null, null),
        new("XBA", "955", "Bond Markets Unit European Composite Unit (EURCO)", null, CurrencyKind.Fund, false, Array.Empty<string>(), null, null),
        new("XBB", "956", "Bond Markets Unit European Monetary Unit (E.M.U.-6)", null, CurrencyKind.Fund, false, Array.Empty<string>(), null, null),
        new("XBC", "957", "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)", null, CurrencyKind.Fund, false, Array.Empty<string>(), null, null),
        new("XBD", "958", "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)", null, CurrencyKind.Fund, false, Array.Empty<string>(), null, null),
        new("XCD", "951", "East Caribbean Dollar", 2, CurrencyKind.NationalCurrency, true, new[] { "AG", "AI", "DM", "GD", "KN", "LC", "MS", "VC" }, null, null),
        new("XCG", "532", "Caribbean Guilder", 2, CurrencyKind.NationalCurrency, true, new[] { "CW", "SX" }, null, null),
        new("XDR", "960", "SDR (Special Drawing Right)", null, CurrencyKind.Fund, false, Array.Empty<string>(), null, null),
        new("XOF", "952", "CFA Franc BCEAO", 0, CurrencyKind.NationalCurrency, true, new[] { "BF", "BJ", "CI", "GW", "ML", "NE", "SN", "TG" }, null, null),
        new("XPD", "964", "Palladium", null, CurrencyKind.PreciousMetal, false, Array.Empty<string>(), null, null),
        new("XPF", "953", "CFP Franc", 0, CurrencyKind.NationalCurrency, true, new[] { "NC", "PF", "WF" }, null, null),
        new("XPT", "962", "Platinum", null, CurrencyKind.PreciousMetal, false, Array.Empty<string>(), null, null),
        new("XSU", "994", "Sucre", null, CurrencyKind.Fund, false, Array.Empty<string>(), null, null),
        new("XTS", "963", "Codes specifically reserved for testing purposes", null, CurrencyKind.Testing, false, Array.Empty<string>(), null, null),
        new("XUA", "965", "ADB Unit of Account", null, CurrencyKind.Fund, false, Array.Empty<string>(), null, null),
        new("XXX", "999", "The codes assigned for transactions where no currency is involved", null, CurrencyKind.NoCurrency, false, Array.Empty<string>(), null, null),
        new("YER", "886", "Yemeni Rial", 2, CurrencyKind.NationalCurrency, true, new[] { "YE" }, null, null),
        new("ZAR", "710", "Rand", 2, CurrencyKind.NationalCurrency, true, new[] { "LS", "NA", "ZA" }, null, null),
        new("ZMW", "967", "Zambian Kwacha", 2, CurrencyKind.NationalCurrency, true, new[] { "ZM" }, null, null),
        new("ZWG", "924", "Zimbabwe Gold", 2, CurrencyKind.NationalCurrency, true, new[] { "ZW" }, null, null)
    };

    public static bool ContainsCode(string code)
    {
        return Entries.Any(entry => string.Equals(entry.Code, code, StringComparison.Ordinal));
    }

    public static IReadOnlyCollection<CurrencyInfo> CreateCurrencyInfos()
    {
        return Entries
            .Select(entry => new CurrencyInfo(
                new CurrencyCode(entry.Code, true),
                entry.NumericCode,
                entry.EnglishName,
                entry.DecimalPlaces.HasValue ? new CurrencyMinorUnit(entry.DecimalPlaces.Value) : CurrencyMinorUnit.NotApplicable,
                entry.Kind,
                entry.IsTender,
                entry.Territories,
                entry.CashDecimalPlaces.HasValue ? new CurrencyMinorUnit(entry.CashDecimalPlaces.Value) : null,
                entry.CashRoundingIncrement))
            .ToArray();
    }

    private sealed class CurrencyDataEntry
    {
        public CurrencyDataEntry(
            string code,
            string numericCode,
            string englishName,
            int? decimalPlaces,
            CurrencyKind kind,
            bool isTender,
            string[] territories,
            int? cashDecimalPlaces = null,
            decimal? cashRoundingIncrement = null)
        {
            Code = code;
            NumericCode = numericCode;
            EnglishName = englishName;
            DecimalPlaces = decimalPlaces;
            Kind = kind;
            IsTender = isTender;
            Territories = territories;
            CashDecimalPlaces = cashDecimalPlaces;
            CashRoundingIncrement = cashRoundingIncrement;
        }

        public string Code { get; }

        public string NumericCode { get; }

        public string EnglishName { get; }

        public int? DecimalPlaces { get; }

        public CurrencyKind Kind { get; }

        public bool IsTender { get; }

        public string[] Territories { get; }

        public int? CashDecimalPlaces { get; }

        public decimal? CashRoundingIncrement { get; }
    }
}
