using System;

namespace ISOCodex.Currency;

// <auto-generated />
// Generated by scripts/update-currency-data.ps1 from data/source/currency-data.manifest.json.
/// <summary>
/// Exposes runtime-visible provenance for the packaged currency data.
/// </summary>
public static class CurrencyDataVersion
{
    /// <summary>Gets the version identifier for the packaged currency data.</summary>
    public static string Identifier { get; } = "seed-2026-06-22-8d366aa7";

    /// <summary>Gets the date this source snapshot was checked, expressed as UTC midnight.</summary>
    public static DateTime CheckedOn { get; } = new DateTime(2026, 6, 22, 0, 0, 0, DateTimeKind.Utc);

    /// <summary>Gets a description of the packaged currency data source.</summary>
    public static string Description { get; } = "Pinned checked-in prerelease seed generated from data/source/currency-data.seed.json; SHA-256 8d366aa7146571ca699f02d1160aecfb0d083941ccb3c7141bc2464738409a35; not a full ISO/CLDR snapshot.";

    /// <summary>Gets the kind of source used for the packaged currency data.</summary>
    public static string SourceKind { get; } = "CheckedInSeed";
}
