using ISOCodex.Currency;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace Currency.Tests;

public class CurrencyDataIntegrityTests
{
    [Fact]
    public void CurrencyCodes_AreUniqueThreeLetterUppercaseAsciiCodes()
    {
        var codes = DefaultCurrencyRegistry.Instance.All.Select(currency => currency.Code.Code).ToArray();

        Assert.All(codes, code => Assert.Matches("^[A-Z]{3}$", code));
        Assert.Equal(codes.Length, codes.Distinct(StringComparer.Ordinal).Count());
    }

    [Fact]
    public void NumericCodes_AreUniqueThreeDigitCodes()
    {
        var numericCodes = DefaultCurrencyRegistry.Instance.All
            .Select(currency => currency.NumericCode)
            .Where(code => !string.IsNullOrWhiteSpace(code))
            .ToArray();

        Assert.All(numericCodes, code => Assert.Matches("^[0-9]{3}$", code));
        Assert.Equal(numericCodes.Length, numericCodes.Distinct(StringComparer.Ordinal).Count());
    }

    [Fact]
    public void MinorUnits_AreValidOrExplicitlyNotApplicable()
    {
        Assert.All(DefaultCurrencyRegistry.Instance.All, currency =>
        {
            if (currency.MinorUnit.IsApplicable)
            {
                Assert.True(currency.MinorUnit.DecimalPlaces >= 0);
                Assert.True(currency.MinorUnit.Increment > 0m);
            }
            else
            {
                Assert.Equal(0m, currency.MinorUnit.Increment);
            }
        });
    }

    [Fact]
    public void EveryRegistryCode_CanBeParsed()
    {
        Assert.All(DefaultCurrencyRegistry.Instance.All, currency =>
        {
            var parsed = CurrencyCode.Parse(currency.Code.Code);

            Assert.Equal(currency.Code, parsed);
        });
    }

    [Fact]
    public void SourceSeed_MatchesRegistryEntries()
    {
        var sourceEntries = LoadSourceSeed();
        var registryEntries = DefaultCurrencyRegistry.Instance.All
            .OrderBy(currency => currency.Code.Code)
            .ToArray();

        Assert.Equal(sourceEntries.Count, registryEntries.Length);

        foreach (var sourceEntry in sourceEntries.OrderBy(entry => entry.Code))
        {
            var currency = Assert.Single(registryEntries, entry => entry.Code.Code == sourceEntry.Code);

            Assert.Equal(sourceEntry.NumericCode, currency.NumericCode);
            Assert.Equal(sourceEntry.EnglishName, currency.EnglishName);
            Assert.Equal(sourceEntry.Kind, currency.Kind.ToString());
            Assert.Equal(sourceEntry.IsTender, currency.IsTender);
            Assert.Equal(sourceEntry.Territories, currency.Territories);

            if (sourceEntry.DecimalPlaces.HasValue)
            {
                Assert.True(currency.MinorUnit.IsApplicable);
                Assert.Equal(sourceEntry.DecimalPlaces.Value, currency.MinorUnit.DecimalPlaces);
            }
            else
            {
                Assert.False(currency.MinorUnit.IsApplicable);
            }

            if (sourceEntry.CashDecimalPlaces.HasValue)
            {
                Assert.True(currency.CashMinorUnit.IsApplicable);
                Assert.Equal(sourceEntry.CashDecimalPlaces.Value, currency.CashMinorUnit.DecimalPlaces);
            }

            Assert.Equal(sourceEntry.CashRoundingIncrement, currency.CashRoundingIncrement);
        }
    }

    [Fact]
    public void SourceManifest_PinsSourceSeed()
    {
        var sourceEntries = LoadSourceSeed();
        var manifest = LoadSourceManifest();
        var source = Assert.Single(manifest.Sources);
        var sourcePath = Path.Combine(new[] { FindRepositoryRoot() }.Concat(source.Path.Split('/')).ToArray());

        Assert.Equal("seed-2026-06-22-7d26419d", manifest.Identifier);
        Assert.Equal("2026-06-22", manifest.CheckedOn);
        Assert.Equal("CheckedInSeed", manifest.SourceKind);
        Assert.Equal(sourceEntries.Count, source.EntryCount);
        Assert.Equal(ComputeNormalizedSha256(sourcePath), source.Sha256);
        Assert.Contains("not a full ISO/CLDR snapshot", manifest.Description);
        Assert.Contains("not an official ISO 4217 redistribution", manifest.RedistributionNotice);
    }

    [Fact]
    public void GeneratedCurrencyData_RecordsSourceSnapshot()
    {
        var generatedFile = Path.Combine(FindRepositoryRoot(), "src", "Currency", "Data", "CurrencyData.generated.cs");
        var generatedText = File.ReadAllText(generatedFile);

        Assert.Contains("Generated by scripts/update-currency-data.ps1 from data/source/currency-data.seed.json.", generatedText);
        Assert.Contains("Pinned by data/source/currency-data.manifest.json.", generatedText);
        Assert.Contains("SourceSnapshot = \"data/source/currency-data.seed.json\"", generatedText);
        Assert.Contains("Normalized source SHA-256: 7d26419d3ac6743023f346dd3d0f91a446f974f51e92b47b161d662d13c5c573", generatedText);
        Assert.Contains("SourceSha256 = \"7d26419d3ac6743023f346dd3d0f91a446f974f51e92b47b161d662d13c5c573\"", generatedText);
        Assert.Contains("SourceEntryCount = 30", generatedText);
    }

    [Fact]
    public void CurrencyDataVersion_RecordsSeedProvenance()
    {
        Assert.Equal("seed-2026-06-22-7d26419d", CurrencyDataVersion.Identifier);
        Assert.Equal(new DateTime(2026, 6, 22, 0, 0, 0, DateTimeKind.Utc), CurrencyDataVersion.CheckedOn);
        Assert.Equal(DateTimeKind.Utc, CurrencyDataVersion.CheckedOn.Kind);
        Assert.Equal("CheckedInSeed", CurrencyDataVersion.SourceKind);
        Assert.Contains("Pinned", CurrencyDataVersion.Description);
        Assert.Contains("SHA-256", CurrencyDataVersion.Description);
        Assert.Contains("checked-in", CurrencyDataVersion.Description);
        Assert.Contains("seed", CurrencyDataVersion.Description);
        Assert.Contains("not a full ISO/CLDR snapshot", CurrencyDataVersion.Description);
    }

    [Fact]
    public void CurrencyDataVersion_DoesNotReplacePackagedRegistryData()
    {
        Assert.True(DefaultCurrencyRegistry.Instance.TryGet(CurrencyCode.GBP, out _));
        Assert.True(DefaultCurrencyRegistry.Instance.TryGet(CurrencyCode.USD, out _));
        Assert.True(DefaultCurrencyRegistry.Instance.TryGet(CurrencyCode.EUR, out _));
    }

    private static IReadOnlyList<CurrencySourceEntry> LoadSourceSeed()
    {
        var path = Path.Combine(FindRepositoryRoot(), "data", "source", "currency-data.seed.json");
        var json = File.ReadAllText(path);
        var entries = JsonSerializer.Deserialize<List<CurrencySourceEntry>>(json, new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true
        });

        return entries ?? throw new InvalidOperationException("Currency data source seed could not be read.");
    }

    private static CurrencySourceManifest LoadSourceManifest()
    {
        var path = Path.Combine(FindRepositoryRoot(), "data", "source", "currency-data.manifest.json");
        var json = File.ReadAllText(path);
        var manifest = JsonSerializer.Deserialize<CurrencySourceManifest>(json, new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true
        });

        return manifest ?? throw new InvalidOperationException("Currency data source manifest could not be read.");
    }

    private static string ComputeNormalizedSha256(string path)
    {
        var text = File.ReadAllText(path);
        var normalizedText = text.Replace("\r\n", "\n").Replace("\r", "\n");
        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(normalizedText));

        return Convert.ToHexString(hash).ToLowerInvariant();
    }

    private static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);

        while (directory != null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "ISOCodex.Currency.sln"))
                && Directory.Exists(Path.Combine(directory.FullName, "data", "source")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new DirectoryNotFoundException("Could not find the repository root.");
    }

    private sealed class CurrencySourceEntry
    {
        public string Code { get; set; } = string.Empty;

        public string NumericCode { get; set; } = string.Empty;

        public string EnglishName { get; set; } = string.Empty;

        public int? DecimalPlaces { get; set; }

        public string Kind { get; set; } = string.Empty;

        public bool IsTender { get; set; }

        public List<string> Territories { get; set; } = new();

        public int? CashDecimalPlaces { get; set; }

        public decimal? CashRoundingIncrement { get; set; }
    }

    private sealed class CurrencySourceManifest
    {
        public string Identifier { get; set; } = string.Empty;

        public string CheckedOn { get; set; } = string.Empty;

        public string SourceKind { get; set; } = string.Empty;

        public string Description { get; set; } = string.Empty;

        public List<CurrencyManifestSource> Sources { get; set; } = new();

        public string RedistributionNotice { get; set; } = string.Empty;
    }

    private sealed class CurrencyManifestSource
    {
        public string Path { get; set; } = string.Empty;

        public string Sha256 { get; set; } = string.Empty;

        public int EntryCount { get; set; }
    }
}
