using ISOCodex.Currency;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Xml.Linq;

namespace Currency.Tests;

public class CurrencyDataIntegrityTests
{
    [Fact]
    public void CurrencyCodes_AreUniqueThreeLetterUppercaseAsciiCodes()
    {
        var codes = DefaultCurrencyRegistry.Instance.All.Select(currency => currency.Code.Code).ToArray();

        Assert.All(codes, code => Assert.Matches("^[A-Z]{3}$", code));
        Assert.Equal(codes.Length, codes.Distinct(StringComparer.Ordinal).Count());
    }

    [Fact]
    public void NumericCodes_AreUniqueThreeDigitCodes()
    {
        var numericCodes = DefaultCurrencyRegistry.Instance.All
            .Select(currency => currency.NumericCode)
            .Where(code => !string.IsNullOrWhiteSpace(code))
            .ToArray();

        Assert.All(numericCodes, code => Assert.Matches("^[0-9]{3}$", code));
        Assert.Equal(numericCodes.Length, numericCodes.Distinct(StringComparer.Ordinal).Count());
    }

    [Fact]
    public void MinorUnits_AreValidOrExplicitlyNotApplicable()
    {
        Assert.All(DefaultCurrencyRegistry.Instance.All, currency =>
        {
            if (currency.MinorUnit.IsApplicable)
            {
                Assert.True(currency.MinorUnit.DecimalPlaces >= 0);
                Assert.True(currency.MinorUnit.Increment > 0m);
            }
            else
            {
                Assert.Equal(0m, currency.MinorUnit.Increment);
            }
        });
    }

    [Fact]
    public void EveryRegistryCode_CanBeParsed()
    {
        Assert.All(DefaultCurrencyRegistry.Instance.All, currency =>
        {
            var parsed = CurrencyCode.Parse(currency.Code.Code);

            Assert.Equal(currency.Code, parsed);
        });
    }

    [Fact]
    public void SourceSnapshot_MatchesRegistryEntries()
    {
        var sourceEntries = LoadSourceSnapshot();
        var registryEntries = DefaultCurrencyRegistry.Instance.All
            .OrderBy(currency => currency.Code.Code)
            .ToArray();

        Assert.Equal(sourceEntries.Count, registryEntries.Length);

        foreach (var sourceEntry in sourceEntries.OrderBy(entry => entry.Code))
        {
            var currency = Assert.Single(registryEntries, entry => entry.Code.Code == sourceEntry.Code);

            Assert.Equal(sourceEntry.NumericCode, currency.NumericCode);
            Assert.Equal(sourceEntry.EnglishName, currency.EnglishName);
            Assert.Equal(sourceEntry.Kind, currency.Kind.ToString());
            Assert.Equal(sourceEntry.IsTender, currency.IsTender);
            Assert.Equal(sourceEntry.Territories, currency.Territories);

            if (sourceEntry.DecimalPlaces.HasValue)
            {
                Assert.True(currency.MinorUnit.IsApplicable);
                Assert.Equal(sourceEntry.DecimalPlaces.Value, currency.MinorUnit.DecimalPlaces);
            }
            else
            {
                Assert.False(currency.MinorUnit.IsApplicable);
            }

            if (sourceEntry.CashDecimalPlaces.HasValue)
            {
                Assert.True(currency.CashMinorUnit.IsApplicable);
                Assert.Equal(sourceEntry.CashDecimalPlaces.Value, currency.CashMinorUnit.DecimalPlaces);
            }

            Assert.Equal(sourceEntry.CashRoundingIncrement, currency.CashRoundingIncrement);
        }
    }

    [Fact]
    public void SourceManifest_PinsFullSourceSnapshot()
    {
        var sourceEntries = LoadSourceSnapshot();
        var manifest = LoadSourceManifest();
        var snapshotSource = Assert.Single(
            manifest.Sources,
            source => source.Path == "data/source/currency-data.snapshot.json");

        Assert.Equal("iso4217-cldr-2026-06-22-c1f3aaea", manifest.Identifier);
        Assert.Equal("2026-06-22", manifest.CheckedOn);
        Assert.Equal("SIX-ISO4217+Unicode-CLDR", manifest.SourceKind);
        Assert.Equal(3, manifest.Sources.Count);
        Assert.Equal(sourceEntries.Count, snapshotSource.EntryCount);
        Assert.Contains("SIX ISO 4217", manifest.Description);
        Assert.Contains("Unicode CLDR", manifest.Description);
        Assert.Contains("not an official ISO 4217 redistribution", manifest.Description);
        Assert.Contains("not an official ISO 4217 redistribution", manifest.RedistributionNotice);

        foreach (var source in manifest.Sources)
        {
            Assert.Equal(ComputeNormalizedSha256(ResolveRepositoryPath(source.Path)), source.Sha256);
        }
    }

    [Fact]
    public void GeneratedCurrencyData_RecordsSourceSnapshot()
    {
        var generatedFile = Path.Combine(FindRepositoryRoot(), "src", "Currency", "Data", "CurrencyData.generated.cs");
        var generatedText = File.ReadAllText(generatedFile);

        Assert.Contains("Generated by scripts/update-currency-data.ps1 from data/source/currency-data.snapshot.json.", generatedText);
        Assert.Contains("Pinned by data/source/currency-data.manifest.json.", generatedText);
        Assert.Contains("SourceSnapshot = \"data/source/currency-data.snapshot.json\"", generatedText);
        Assert.Contains("Normalized source SHA-256: c1f3aaea54949be9a7399a105dd61917a293dafb73171b9c1d3f6cf0b9179f95", generatedText);
        Assert.Contains("SourceSha256 = \"c1f3aaea54949be9a7399a105dd61917a293dafb73171b9c1d3f6cf0b9179f95\"", generatedText);
        Assert.Contains("SourceEntryCount = 178", generatedText);
    }

    [Fact]
    public void CurrencyDataVersion_RecordsFullSnapshotProvenance()
    {
        Assert.Equal("iso4217-cldr-2026-06-22-c1f3aaea", CurrencyDataVersion.Identifier);
        Assert.Equal(new DateTime(2026, 6, 22, 0, 0, 0, DateTimeKind.Utc), CurrencyDataVersion.CheckedOn);
        Assert.Equal(DateTimeKind.Utc, CurrencyDataVersion.CheckedOn.Kind);
        Assert.Equal("SIX-ISO4217+Unicode-CLDR", CurrencyDataVersion.SourceKind);
        Assert.Contains("Pinned", CurrencyDataVersion.Description);
        Assert.Contains("SIX ISO 4217", CurrencyDataVersion.Description);
        Assert.Contains("Unicode CLDR", CurrencyDataVersion.Description);
        Assert.Contains("SHA-256", CurrencyDataVersion.Description);
        Assert.Contains("not an official ISO 4217 redistribution", CurrencyDataVersion.Description);
    }

    [Fact]
    public void CurrencyDataVersion_DoesNotReplacePackagedRegistryData()
    {
        Assert.True(DefaultCurrencyRegistry.Instance.TryGet(CurrencyCode.GBP, out _));
        Assert.True(DefaultCurrencyRegistry.Instance.TryGet(CurrencyCode.USD, out _));
        Assert.True(DefaultCurrencyRegistry.Instance.TryGet(CurrencyCode.EUR, out _));
    }

    [Fact]
    public void SourceSnapshot_IncludesEverySIXListOneCurrencyCode()
    {
        var sourceCodes = LoadSourceSnapshot()
            .Select(entry => entry.Code)
            .Order(StringComparer.Ordinal)
            .ToArray();
        var isoCodes = LoadIsoListOneCurrencyCodes()
            .Order(StringComparer.Ordinal)
            .ToArray();

        Assert.Equal(178, sourceCodes.Length);
        Assert.Equal(isoCodes, sourceCodes);
    }

    [Fact]
    public void SourceSnapshot_UsesCldrCashFractionMetadata()
    {
        var huf = DefaultCurrencyRegistry.Instance.Get(CurrencyCode.Parse("HUF"));
        var chf = DefaultCurrencyRegistry.Instance.Get(CurrencyCode.CHF);
        var cad = DefaultCurrencyRegistry.Instance.Get(CurrencyCode.Parse("CAD"));

        Assert.Equal(2, huf.MinorUnit.DecimalPlaces);
        Assert.Equal(0, huf.CashMinorUnit.DecimalPlaces);
        Assert.Equal(5m, huf.CashRoundingIncrement);

        Assert.Equal(2, chf.CashMinorUnit.DecimalPlaces);
        Assert.Equal(0.05m, chf.CashRoundingIncrement);

        Assert.Equal(2, cad.CashMinorUnit.DecimalPlaces);
        Assert.Equal(0.05m, cad.CashRoundingIncrement);
    }

    private static IReadOnlyList<CurrencySourceEntry> LoadSourceSnapshot()
    {
        var path = Path.Combine(FindRepositoryRoot(), "data", "source", "currency-data.snapshot.json");
        var json = File.ReadAllText(path);
        var entries = JsonSerializer.Deserialize<List<CurrencySourceEntry>>(json, new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true
        });

        return entries ?? throw new InvalidOperationException("Currency data source snapshot could not be read.");
    }

    private static CurrencySourceManifest LoadSourceManifest()
    {
        var path = Path.Combine(FindRepositoryRoot(), "data", "source", "currency-data.manifest.json");
        var json = File.ReadAllText(path);
        var manifest = JsonSerializer.Deserialize<CurrencySourceManifest>(json, new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true
        });

        return manifest ?? throw new InvalidOperationException("Currency data source manifest could not be read.");
    }

    private static string ComputeNormalizedSha256(string path)
    {
        var text = File.ReadAllText(path);
        var normalizedText = text.Replace("\r\n", "\n").Replace("\r", "\n");
        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(normalizedText));

        return Convert.ToHexString(hash).ToLowerInvariant();
    }

    private static IReadOnlySet<string> LoadIsoListOneCurrencyCodes()
    {
        var document = XDocument.Load(ResolveRepositoryPath("data/source/upstream/six/list-one.xml"));

        return document
            .Descendants("CcyNtry")
            .Select(entry => entry.Element("Ccy")?.Value)
            .Where(code => !string.IsNullOrWhiteSpace(code))
            .Select(code => code!)
            .ToHashSet(StringComparer.Ordinal);
    }

    private static string ResolveRepositoryPath(string relativePath)
    {
        return Path.Combine(new[] { FindRepositoryRoot() }.Concat(relativePath.Split('/')).ToArray());
    }

    private static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);

        while (directory != null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "ISOCodex.Currency.sln"))
                && Directory.Exists(Path.Combine(directory.FullName, "data", "source")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new DirectoryNotFoundException("Could not find the repository root.");
    }

    private sealed class CurrencySourceEntry
    {
        public string Code { get; set; } = string.Empty;

        public string NumericCode { get; set; } = string.Empty;

        public string EnglishName { get; set; } = string.Empty;

        public int? DecimalPlaces { get; set; }

        public string Kind { get; set; } = string.Empty;

        public bool IsTender { get; set; }

        public List<string> Territories { get; set; } = new();

        public int? CashDecimalPlaces { get; set; }

        public decimal? CashRoundingIncrement { get; set; }
    }

    private sealed class CurrencySourceManifest
    {
        public string Identifier { get; set; } = string.Empty;

        public string CheckedOn { get; set; } = string.Empty;

        public string SourceKind { get; set; } = string.Empty;

        public string Description { get; set; } = string.Empty;

        public List<CurrencyManifestSource> Sources { get; set; } = new();

        public string RedistributionNotice { get; set; } = string.Empty;
    }

    private sealed class CurrencyManifestSource
    {
        public string Path { get; set; } = string.Empty;

        public string Sha256 { get; set; } = string.Empty;

        public int? EntryCount { get; set; }
    }
}
