param(
    [string] $SourcePath = "data/source/currency-data.seed.json",
    [string] $OutputPath = "src/Currency/Data/CurrencyData.generated.cs"
)

$ErrorActionPreference = "Stop"

function Format-CSharpString {
    param([string] $Value)

    return '"' + ($Value -replace '\\', '\\' -replace '"', '\"') + '"'
}

function Format-NullableInt {
    param($Value)

    if ($null -eq $Value) {
        return "null"
    }

    return [string][int]$Value
}

function Format-NullableDecimal {
    param($Value)

    if ($null -eq $Value) {
        return "null"
    }

    return ([decimal]$Value).ToString([Globalization.CultureInfo]::InvariantCulture) + "m"
}

function Format-Territories {
    param($Territories)

    if ($null -eq $Territories -or $Territories.Count -eq 0) {
        return "Array.Empty<string>()"
    }

    $items = @($Territories | ForEach-Object { Format-CSharpString $_ })
    return "new[] { " + ($items -join ", ") + " }"
}

$source = Resolve-Path $SourcePath
$output = Join-Path (Get-Location) $OutputPath
$entries = Get-Content -LiteralPath $source -Raw | ConvertFrom-Json

$seenCodes = @{}
$seenNumericCodes = @{}

foreach ($entry in $entries) {
    if ($entry.code -notmatch '^[A-Z]{3}$') {
        throw "Invalid currency code '$($entry.code)'."
    }

    if ($entry.numericCode -notmatch '^[0-9]{3}$') {
        throw "Invalid numeric code '$($entry.numericCode)' for '$($entry.code)'."
    }

    if ($seenCodes.ContainsKey($entry.code)) {
        throw "Duplicate currency code '$($entry.code)'."
    }

    if ($seenNumericCodes.ContainsKey($entry.numericCode)) {
        throw "Duplicate numeric code '$($entry.numericCode)'."
    }

    $seenCodes[$entry.code] = $true
    $seenNumericCodes[$entry.numericCode] = $true

    if ($null -ne $entry.decimalPlaces -and [int]$entry.decimalPlaces -lt 0) {
        throw "Invalid decimal places for '$($entry.code)'."
    }
}

$lines = [Collections.Generic.List[string]]::new()
$lines.Add("using System;")
$lines.Add("using System.Collections.Generic;")
$lines.Add("using System.Linq;")
$lines.Add("")
$lines.Add("namespace ISOCodex.Currency;")
$lines.Add("")
$lines.Add("// <auto-generated />")
$lines.Add("// Generated by scripts/update-currency-data.ps1 from data/source/currency-data.seed.json.")
$lines.Add("// Review data/source/README.md before changing the source snapshot.")
$lines.Add("internal static class CurrencyData")
$lines.Add("{")
$lines.Add("    internal const string SourceSnapshot = `"data/source/currency-data.seed.json`";")
$lines.Add("")
$lines.Add("    private static readonly CurrencyDataEntry[] Entries =")
$lines.Add("    {")

for ($i = 0; $i -lt $entries.Count; $i++) {
    $entry = $entries[$i]
    $suffix = if ($i -eq $entries.Count - 1) { "" } else { "," }
    $cashDecimalPlaces = Format-NullableInt $entry.cashDecimalPlaces
    $cashRoundingIncrement = Format-NullableDecimal $entry.cashRoundingIncrement

    $line = "        new($((Format-CSharpString $entry.code)), $((Format-CSharpString $entry.numericCode)), $((Format-CSharpString $entry.englishName)), $((Format-NullableInt $entry.decimalPlaces)), CurrencyKind.$($entry.kind), $($entry.isTender.ToString().ToLowerInvariant()), $((Format-Territories $entry.territories)), $cashDecimalPlaces, $cashRoundingIncrement)$suffix"
    $lines.Add($line)
}

$lines.Add("    };")
$lines.Add("")
$lines.Add("    public static bool ContainsCode(string code)")
$lines.Add("    {")
$lines.Add("        return Entries.Any(entry => string.Equals(entry.Code, code, StringComparison.Ordinal));")
$lines.Add("    }")
$lines.Add("")
$lines.Add("    public static IReadOnlyCollection<CurrencyInfo> CreateCurrencyInfos()")
$lines.Add("    {")
$lines.Add("        return Entries")
$lines.Add("            .Select(entry => new CurrencyInfo(")
$lines.Add("                new CurrencyCode(entry.Code, true),")
$lines.Add("                entry.NumericCode,")
$lines.Add("                entry.EnglishName,")
$lines.Add("                entry.DecimalPlaces.HasValue ? new CurrencyMinorUnit(entry.DecimalPlaces.Value) : CurrencyMinorUnit.NotApplicable,")
$lines.Add("                entry.Kind,")
$lines.Add("                entry.IsTender,")
$lines.Add("                entry.Territories,")
$lines.Add("                entry.CashDecimalPlaces.HasValue ? new CurrencyMinorUnit(entry.CashDecimalPlaces.Value) : null,")
$lines.Add("                entry.CashRoundingIncrement))")
$lines.Add("            .ToArray();")
$lines.Add("    }")
$lines.Add("")
$lines.Add("    private sealed class CurrencyDataEntry")
$lines.Add("    {")
$lines.Add("        public CurrencyDataEntry(")
$lines.Add("            string code,")
$lines.Add("            string numericCode,")
$lines.Add("            string englishName,")
$lines.Add("            int? decimalPlaces,")
$lines.Add("            CurrencyKind kind,")
$lines.Add("            bool isTender,")
$lines.Add("            string[] territories,")
$lines.Add("            int? cashDecimalPlaces = null,")
$lines.Add("            decimal? cashRoundingIncrement = null)")
$lines.Add("        {")
$lines.Add("            Code = code;")
$lines.Add("            NumericCode = numericCode;")
$lines.Add("            EnglishName = englishName;")
$lines.Add("            DecimalPlaces = decimalPlaces;")
$lines.Add("            Kind = kind;")
$lines.Add("            IsTender = isTender;")
$lines.Add("            Territories = territories;")
$lines.Add("            CashDecimalPlaces = cashDecimalPlaces;")
$lines.Add("            CashRoundingIncrement = cashRoundingIncrement;")
$lines.Add("        }")
$lines.Add("")
$lines.Add("        public string Code { get; }")
$lines.Add("")
$lines.Add("        public string NumericCode { get; }")
$lines.Add("")
$lines.Add("        public string EnglishName { get; }")
$lines.Add("")
$lines.Add("        public int? DecimalPlaces { get; }")
$lines.Add("")
$lines.Add("        public CurrencyKind Kind { get; }")
$lines.Add("")
$lines.Add("        public bool IsTender { get; }")
$lines.Add("")
$lines.Add("        public string[] Territories { get; }")
$lines.Add("")
$lines.Add("        public int? CashDecimalPlaces { get; }")
$lines.Add("")
$lines.Add("        public decimal? CashRoundingIncrement { get; }")
$lines.Add("    }")
$lines.Add("}")

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $output) | Out-Null
$utf8NoBom = [Text.UTF8Encoding]::new($false)
[IO.File]::WriteAllLines($output, $lines, $utf8NoBom)

Write-Host "Generated $OutputPath from $SourcePath ($($entries.Count) entries)."
